from ast.node import *
from ast.assignment import *
from ast.binop import *
from ast.varref import *
from ast.conditional import *
from ast.procedure import *
from ast.ret import *
from ast.call import *
from ast.alloc import *
from ast.gvar import *
